<?php
/**
 * @file
 * Install, update and uninstall functions for the ie_meta_tag module.
 */

/**
 * Implements hook_uninstall().
 *
 * @ingroup ie_meta_tag
 */
function ie_meta_tag_uninstall() {
  variable_del('ie_meta_tag_enabled');
  variable_del('ie_meta_tag_method'),
  variable_del('ie_meta_tag_ie_flavor'),
  variable_del('ie_meta_tag_ie_chrome_option')
  variable_del('ie_meta_tag_weight')
  variable_del('ie_meta_tag_debug_message');
  variable_del('ie_meta_tag_debug_reporting');
}
